/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface LachsButton {
    }
    interface LachsLink {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLLachsButtonElement extends Components.LachsButton, HTMLStencilElement {
    }
    var HTMLLachsButtonElement: {
        prototype: HTMLLachsButtonElement;
        new (): HTMLLachsButtonElement;
    };
    interface HTMLLachsLinkElement extends Components.LachsLink, HTMLStencilElement {
    }
    var HTMLLachsLinkElement: {
        prototype: HTMLLachsLinkElement;
        new (): HTMLLachsLinkElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "lachs-button": HTMLLachsButtonElement;
        "lachs-link": HTMLLachsLinkElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface LachsButton {
    }
    interface LachsLink {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "lachs-button": LachsButton;
        "lachs-link": LachsLink;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "lachs-button": LocalJSX.LachsButton & JSXBase.HTMLAttributes<HTMLLachsButtonElement>;
            "lachs-link": LocalJSX.LachsLink & JSXBase.HTMLAttributes<HTMLLachsLinkElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
